### PR TITLE
More improvements as I read the book

### PR DESCRIPTION
**Pull request by ujos**
Sorry for huge commits set. If you think it makes sense to create many pull request instead of one with many commits, please let me know

### CODE REVIEW

**Comment by burlachenkok** [comment]
Thank you so much! Really. I did it as a hobby, it does not give me extra credits as a Ph.D. student at KAUST, Saudi Arabia,

However, the impact and scope of C++ are huge. So I think having good technical notes covering C++ technical details is a good thing to have. What I personally do not like - is very-very often people select Python because learning C++ is a thing by itself, and "people do not have time for that" and I do not like that.

Thank you very much for your valuable contributions! I will inspect it, but a bit later. Right now I'm not a vacation.

**Comment by ujos** [comment]
Wait a sec... I incorrectly fixed conflicts

**Comment by burlachenkok** [comment]
I have merged.

**Comment by burlachenkok** [comment]
I think the issue was with `decltype` - I will fix by hands.

**Comment by ujos** [comment]
```diff
- The close by conception is `decltype` keyword. It provides ability to derive type of expression without evaluating it.
 -The close-by conception is [decltype](https://en.cppreference.com/w/cpp/language/decltype). It provides the ability to derive the type of expression without eval
uating it.  There are some subtleties with `decltype`. In fact, `decltype(x)` and `decltype((x))` are often different types. If the argument is an unparenthesized
expression or an unparenthesized class member access expression, then [decltype](https://en.cppreference.com/w/cpp/language/decltype) yields the type of the entity
 named by this expression. The inner parentheses cause the statement to be evaluated as an expression.
```

I've accidentally removed the text above

**Comment by burlachenkok** [comment]
Ok. Do not worry. I will polish it.

**Comment by burlachenkok** [comment]
Special thanks for fixing TOC.

**Comment by ujos** [comment]
> very-very often people select Python because learning C++ is a thing by itself, and "people do not have time for that" and I do not like that.

That is totally OK. ***Right tool for right job***. 

* Python is for scientists. They need to check their idea quickly. They are not going to support that code.
* C++ is for developers who implement functionality and support it for long time. C++ if perfect for that purpose as it has static type system and compile time validation

**Comment by burlachenkok** [comment]
Thanks. For sharing comment. But in my experience it's a bit more complicated:

* It depend on scientists, a lot of scientist at NVIDIA create code in C++, because they need to be aware of system level :)
* A lot of scientist in HPC need to create code in C++ because the C/C++ was defacto for a long time.
* Some scientific groups in R&D does not have a lot of resources so they also mix research development and productization.

Let's put that into separate issue.

From another side to create prototype for some system when (huge CAD, enviroment) is exist and create things in C++ - it can take years.

**Comment by burlachenkok** [comment]
> very-very often people select Python because learning C++ is a thing by itself, and "people do not have time for that" and I do not like that.

My mistake. I thought that it was in the the text, only in comments in that issue.
Thanks one more time for contribution.

**Pull request merged**
