### PR TITLE
Align nested elemens of the (un)ordered lists and better wording

### PR DESCRIPTION
**Pull request by ujos**

### CODE REVIEW

**Comment by burlachenkok** [comment]
Thank you very much for polishing!

**Comment by burlachenkok** [comment]
@ujos please let me know if you want to share your academic/industrial affiliation.

**Comment by burlachenkok** [comment]
Sounds very nice! Please, let me know if you have no objections if I will add your affiliation explicitly ?

**Comment by ujos** [comment]
Sure, no problem. Please add

**Comment by burlachenkok** [comment]
Done. Thanks.

**Pull request merged**
